@startuml
scale 1 as 100 pixels
concise create_network0
concise create_instance0
concise create_instance1
concise create_instance2
concise create_object0
concise create_object1
concise create_volume0
concise create_instance3

@create_instance0
3 is "Create instances"
6 is {hidden}

@create_instance1
3 is "Create instances"
6 is {hidden}

@create_instance2
3 is "Create instances"
8 is {hidden}

@create_instance3
6 is "Create database"
9 is {hidden}

@create_network0
0 is "Create network"
3 is {hidden}

@create_object0
3 is "Create object"
6 is {hidden}

@create_object1
3 is "Create network object"
6 is {hidden}

@create_volume0
3 is "Create storage"
6 is {hidden}
@enduml
