@startuml
scale 1 as 20 pixels
concise create_network0
concise create_instance0
concise create_instance1
concise create_instance2
concise create_object0
concise create_object1
concise create_volume0
concise create_instance3

@create_instance0
18 is "Create instances"
36 is {hidden}

@create_instance1
18 is "Create instances"
36 is {hidden}

@create_instance2
18 is "Create instances"
45 is {hidden}

@create_instance3
35 is "Create database"
49 is {hidden}

@create_network0
0 is "Create network"
18 is {hidden}

@create_object0
18 is "Create object"
36 is {hidden}

@create_object1
18 is "Create network object"
31 is {hidden}

@create_volume0
18 is "Create storage"
35 is {hidden}
@enduml
